### ISSUE TITLE
[FR] Autodect creating an output folder upon decompression

### ISSUE THREAD

**Issue by murlakatamenka** [ouch-org/ouch#169] opened 2021-11-07 12:50 UTC
Since ouch is focused on ease of use and ergonomics I suggest to consider implementing the following flag for decompression.

[KDE's Ark](https://apps.kde.org/ark/) has `-a, --autosubfolder` flag:

> Archive contents will be read, and if detected  not be a single folder or a single file  a subfolder with the name of the will be created.

I use it all the time :smile: and find it really helpful for unarchiving stuff blindly, without preview.

**Comment by SpyrosRoum** [comment] 2021-11-07 13:05
This is a duplicate of #151 but I agree it's a nice QoL to have

**Comment by murlakatamenka** [comment] 2021-11-07 13:57
Yeah, right, that's essentially a duplicate.

**Comment by marcospb19** [comment] 2021-11-08 21:23
Will be taking a look at it tho.

**Closed** 2021-11-08 21:23 UTC
Labels: duplicate
