### ISSUE TITLE
No path completion when using the short alias on ZSH

### ISSUE THREAD

**Issue by hunkyburrito** [ouch-org/ouch#737] opened 2024-11-16 01:26 UTC
### Version

0.5.1

### Description

Using the short alias (like d instead of decompress) prevents path completion from being available afterwards in ZSH.

### Current Behavior

Typing `ouch d <TAB>` shows no completion options, but typing `ouch decompress <TAB>` shows path completion options.

### Expected Behavior

Typing `ouch d <TAB>` shows the same completion options as the long form.

### Additional Information

I have only tested on zsh, and am unsure if the same happens with other shells like bash or fish.

**Comment by marcospb19** [comment] 2024-11-16 04:27
ty for the issue

duplicate of #357

**Closed by marcospb19** 2024-11-16 04:27 UTC
Labels: bug
